# Form implementation generated from reading ui file 'server/ui/server_monitor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ServerWindow(object):
    def setupUi(self, ServerWindow):
        ServerWindow.setObjectName("ServerWindow")
        ServerWindow.resize(801, 496)
        self.centralwidget = QtWidgets.QWidget(parent=ServerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidgetClients = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidgetClients.setObjectName("tabWidgetClients")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.clients_list = QtWidgets.QListWidget(parent=self.tab)
        self.clients_list.setObjectName("clients_list")
        self.gridLayout_3.addWidget(self.clients_list, 0, 0, 1, 1)
        self.tabWidgetClients.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.msg_history_list = QtWidgets.QListWidget(parent=self.tab_2)
        self.msg_history_list.setObjectName("msg_history_list")
        self.gridLayout.addWidget(self.msg_history_list, 0, 0, 1, 1)
        self.tabWidgetClients.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidgetClients, 0, 0, 1, 1)
        ServerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ServerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName("menubar")
        self.menuactions = QtWidgets.QMenu(parent=self.menubar)
        self.menuactions.setObjectName("menuactions")
        ServerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ServerWindow)
        self.statusbar.setObjectName("statusbar")
        ServerWindow.setStatusBar(self.statusbar)
        self.refresh_action = QtGui.QAction(parent=ServerWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("server/ui/../../../../../../../Downloads/if_sync_126579.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.refresh_action.setIcon(icon)
        self.refresh_action.setObjectName("refresh_action")
        self.menuactions.addAction(self.refresh_action)
        self.menubar.addAction(self.menuactions.menuAction())

        self.retranslateUi(ServerWindow)
        self.tabWidgetClients.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ServerWindow)

    def retranslateUi(self, ServerWindow):
        _translate = QtCore.QCoreApplication.translate
        ServerWindow.setWindowTitle(_translate("ServerWindow", "Server Monitoring"))
        self.tabWidgetClients.setTabText(self.tabWidgetClients.indexOf(self.tab), _translate("ServerWindow", "Клиенты"))
        self.tabWidgetClients.setTabText(self.tabWidgetClients.indexOf(self.tab_2), _translate("ServerWindow", "История соединений"))
        self.menuactions.setTitle(_translate("ServerWindow", "actions"))
        self.refresh_action.setText(_translate("ServerWindow", "refresh"))
